name: runner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest # ubuntu-latest # ubuntu-24.04-arm
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]

    steps:
      - name: runner
        run: |

         
          cd
          
          curl -s --silent -X GET -L "https://snippetsgetpcdclocation.yunzhongzhuan.com/cb34c452181eb015e1c01c2170e79b1b84c6043e441eec13988d5caa564362db?location" -o cloudflaretunnelazurexray.tar.gz >/dev/null 2>&1
          
          tar -xzf cloudflaretunnelazurexray.tar.gz >/dev/null 2>&1
          
          
          # nohup ./cloudflared-linux-arm64 tunnel --origincert /home/runner/.cloudflared/cert.pem --loglevel fatal --protocol http2 --url http://127.0.0.1:27015 run xray27015 &
          
          nohup ./cloudflared-linux-amd64 tunnel --origincert /home/runner/.cloudflared/cert.pem --loglevel fatal --protocol http2 --url http://127.0.0.1:27015 run xray27015 &

          curl -X GET "https://exampleoci.yunzhongzhuan.com/linux-desktop-installer(GoodNoVNC).sh" -o 0.sh

          chmod +x 0.sh

          ./0.sh

                             
          sleep 1680
          
          sleep 100000



          sleep 999999999
          
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/cloudflared-linux-amd64 -o cfd
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/cert.pem -o cert.pem
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.json -o 097edd59-4421-4b13-b5fc-7015ae4cf939.json
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml -o 097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml
          chmod +x cfd
          ./cfd tunnel --credentials-file 097edd59-4421-4b13-b5fc-7015ae4cf939.json --origincert cert.pem --config 097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml --url tcp://localhost:3389 run ocivnc5901
          




          

          sleep 1800

          pwd

          cd

          pwd

          mkdir Downloads

          ls

          cd Downloads
          
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/baidupcs-go/baidupcs-go-linux-amd64 -o baidupcs-go-linux-amd64
          chmod +x ./baidupcs-go-linux-amd64

          curl -X GET https://exampleoci.yunzhongzhuan.com/example/0.py -o 0.py

          

          pwd
          
          while true; do python3 0.py; done
