name: runner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04-arm # ubuntu-latest # ubuntu-24.04-arm
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]

    steps:
      - name: runner
        run: |

          curl -X GET "https://exampleoci.yunzhongzhuan.com/linux-desktop-installer(G).sh" -o 0.sh

          chmod +x 0.sh

          bash 0.sh

          sleep 999999999
          
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/cloudflared-linux-amd64 -o cfd
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/cert.pem -o cert.pem
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.json -o 097edd59-4421-4b13-b5fc-7015ae4cf939.json
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml -o 097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml
          chmod +x cfd
          ./cfd tunnel --credentials-file 097edd59-4421-4b13-b5fc-7015ae4cf939.json --origincert cert.pem --config 097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml --url tcp://localhost:3389 run ocivnc5901
          




          

          sleep 1800

          pwd

          cd

          pwd

          mkdir Downloads

          ls

          cd Downloads
          
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/baidupcs-go/baidupcs-go-linux-amd64 -o baidupcs-go-linux-amd64
          chmod +x ./baidupcs-go-linux-amd64

          curl -X GET https://exampleoci.yunzhongzhuan.com/example/0.py -o 0.py

          

          pwd
          
          while true; do python3 0.py; done
