name: runner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]

    steps:
      - name: runner
        run: |
          cd
          curl -X GET "https://www.bigfile.net/d/4wzlCrxa8nO1OLFAZ6tUgRN6sLPu5v8RizS7k7CMU5r/backup.tar.gz?content-type=application%2Fgzip" -o 0.tar.gz
          tar -xzvf ./0.tar.gz
          cat ./run.sh
          ls -la
          ./aria2c --conf-path=/home/runner/aria2c_config.conf &
          ./cloudreve -c cloudreve_config.conf &
          sleep 10
          ./cloudflared-linux-amd64 tunnel --origincert /home/runner/.cloudflared/cert.pem --loglevel fatal --protocol http2 --url http://127.0.0.1:5212 run xray27015
          
          # chmod +x ./run.sh
          # bash ./run.sh
          sleep 99999999
