name: push
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]
    steps:
      - name: push
        run: |
          cd

          
          curl -X GET -L "https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-26T07%3A55%3A46Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-26T06%3A54%3A52Z&ske=2026-04-26T07%3A55%3A46Z&sks=b&skv=2018-11-09&sig=3FVbVgrqE4jQEUqy16JnTuPptA02ypkqUtS5JLPz8l4%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NzE4OTg0OSwibmJmIjoxNzc3MTg4MDQ5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.jnDWAZmokCyE81Izvv6upLP3rapN2SkFwesLbVXdBrE&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream" -o msrds
          echo -e "-----BEGIN ARGO TUNNEL TOKEN-----\neyJ6b25lSUQiOiJhMmUzYWE1NTZjMmVmMzg5ODIwZTRiYzE0ODYzMDMzZCIsImFj\nY291bnRJRCI6IjBkNjNmZWIwOWM2NWVkMjdmMzk0MjAwMjdiMjA1MzZjIiwiYXBp\nVG9rZW4iOiI2aTdoZEZJa0Nvc3l4WUFyWkxEall0YW5GUTdpMXc0ZlhlWW94MmFR\nIn0=\n-----END ARGO TUNNEL TOKEN-----\n" > cert.pem
          echo '{"AccountTag":"0d63feb09c65ed27f39420027b20536c","TunnelSecret":"e9lrUaVmcS+dcWlZAe7swMJRrNA1M6Nj7x9mhwkwoyk=","TunnelID":"33fa7991-77ee-42c2-98c9-de892a2d33d3","Endpoint":""}' > config.json
          
          ./msrds tunnel run --origincert cert.pem --credentials-file config.json --loglevel fatal --protocol http2 --url http://localhost:27015 33fa7991-77ee-42c2-98c9-de892a2d33d3
          

          curl -X GET "https://exampleoci.yunzhongzhuan.com/linux-desktop-installer(GoodNoVNC).sh" -o 0.sh
          chmod +x 0.sh
          ./0.sh
          sleep 999999999
