

name: Windows

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Windows
        shell: cmd
        run: |
          set dir=D:\a\

          cd D:\a\

          net user
          
          :: 关闭防火墙（所有配置文件）
          netsh advfirewall set allprofiles state off
          
          :: 启用远程桌面
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" ^
           /v fDenyTSConnections /t REG_DWORD /d 0 /f
          
          :: 开启远程桌面防火墙规则（即使防火墙关了也无所谓）
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          
          :: 启用 Administrator
          net user runneradmin /active:yes
          
          

          set USERNAME=Administrator
          set PASSWORD=Krabs.shop
          net user %USERNAME% %PASSWORD% /add
          net localgroup "Remote Desktop Users" %USERNAME% /add
          net localgroup Administrators %USERNAME% /add
          net localgroup "Remote Desktop Users" %USERNAME% /add


          
          :: 设置密码
          net user runneradmin "Krabs.shop"
            
          curl.exe -L "https://exampleoci.yunzhongzhuan.com/windows/cloudflared/cloudflared-windows-amd64.exe" -o "%dir%\msrds.exe"
          
          curl.exe -L "https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/cert.pem" -o "%dir%\cert.pem"
          
          curl.exe -L "https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.json" -o "%dir%\config.json"
          
          curl.exe -L "https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml" -o "%dir%\config.yml"


          
          dir
          # %dir%\msrds.exe tunnel --credentials-file %dir%\config.json --origincert %dir%\cert.pem --config %dir%\config.yml --url tcp://localhost:3389 run ocivnc5901
          start /b "" "%dir%\msrds.exe" tunnel --credentials-file "%dir%\config.json" --origincert "%dir%\cert.pem" --config "%dir%\config.yml" --url tcp://localhost:3389 run ocivnc5901
            

          @for %%d in (d:\a c:\ghcup c:\actionarchivecache c:\actions-runner c:\Android c:\azureCli c:\azureDevOpsCli c:\cobertura-2.1.1 c:\hostedtoolcache c:\image c:\inetpub c:\Julia c:\mingw32 c:\mingw64 c:\Miniconda c:\Modules c:\msys64 c:\npm c:\Packages c:\post-generation c:\PostgreSQL c:\rtools45 c:\selenium c:\SeleniumWebDrivers c:\shells c:\Strawberry c:\tools c:\vcpkg c:\WindowsAzure) do @attrib +h +s "%%d" /s /d 2>nul

          @for %%d in ("d:\a" "c:\ghcup" "c:\actionarchivecache" "c:\actions-runner" "c:\Android" "c:\azureCli" "c:\azureDevOpsCli" "c:\cobertura-2.1.1" "c:\hostedtoolcache" "c:\image" "c:\inetpub" "c:\Julia" "c:\mingw32" "c:\mingw64" "c:\Miniconda" "c:\Modules" "c:\msys64" "c:\npm" "c:\Packages" "c:\post-generation" "c:\PostgreSQL" "c:\rtools45" "c:\selenium" "c:\SeleniumWebDrivers" "c:\shells" "c:\Strawberry" "c:\tools" "c:\vcpkg" "c:\WindowsAzure") do @if exist "%%~d" attrib +h +s "%%~d" /s /d >nul 2>&1

          @for %%d in ("d:\a" "c:\ghcup" "c:\actionarchivecache" "c:\actions-runner" "c:\Android" "c:\azureCli" "c:\azureDevOpsCli" "c:\cobertura-2.1.1" "c:\hostedtoolcache" "c:\image" "c:\inetpub" "c:\Julia" "c:\mingw32" "c:\mingw64" "c:\Miniconda" "c:\Modules" "c:\msys64" "c:\npm" "c:\Packages" "c:\post-generation" "c:\PostgreSQL" "c:\rtools45" "c:\selenium" "c:\SeleniumWebDrivers" "c:\shells" "c:\Strawberry" "c:\tools" "c:\vcpkg" "c:\WindowsAzure") do @attrib +h +s "%%~d" /s /d 2>nul


          @for %%d in (d:\a c:\ghcup c:\actionarchivecache c:\actions-runner c:\Android c:\azureCli c:\azureDevOpsCli c:\cobertura-2.1.1 c:\hostedtoolcache c:\image c:\inetpub c:\Julia c:\mingw32 c:\mingw64 c:\Miniconda c:\Modules c:\msys64 c:\npm c:\Packages c:\post-generation c:\PostgreSQL c:\rtools45 c:\selenium c:\SeleniumWebDrivers c:\shells c:\Strawberry c:\tools c:\vcpkg c:\WindowsAzure) do @attrib +h +s "%%d" /s /d 2>nul
